### ISSUE TITLE
Set up test coverage

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#10]
We also need to find a way to track this metric.

**Comment by stefanceriu** [comment]
The test github action is now setup for both unit and ui tests and it's printing out coverage reports in the console through fastlane's xcov. We tried piping the results into Danger swift's coverage plugin but it would just silently fail. In the end we decided to use codecov.io especially as other matrix projects are using it. We're currently waiting for it to receive access to the vector-im organization.

**Comment by stefanceriu** [comment]
Change of plans, we will use sonarcloud.io instead - https://sonarcloud.io/organizations/new_vector_ltd_organization/projects

**Comment by stefanceriu** [comment]
After setting this up SonarCould is unfortunately not a good option. It cannot analyse ObjC files without [using a custom build wrapper](https://docs.sonarqube.org/latest/analysis/languages/cfamily/) and ignoring those files makes it fail parsing the coverage report: `Line 37382 of report refers to a file with an unknown language: ElementX/Sources/Other/HTMLParsing/UIFont+AttributedStringBuilder.m`

Adding a dependency to a custom build wrapper is not something that we should introduce. Codecov seems to only require the test result bundle so that seems like a better alternative.

**Comment by manuroe** [comment]
We have [codecov](https://app.codecov.io/gh/vector-im/element-x-ios) now. The coverage is currently at 46% and it is increasing.
