### ISSUE TITLE
push notifs can break view stack

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1140]
### Steps to reproduce

1. start inviting someone to a room
2. push notif comes in
3. accidentally tap the notif
4. room in the background invisibly changes to show the push notif
5. finish inviting the user
6. hit invite button
7. nothing happens
8. cancel out and discover you’re in the room from the push notif

#### What did you expect?

opening a push should cancel other UI open in the app, not break the UI.

#### What happened instead?

the room view changed to the push but UI on too didn’t

### Application version

244

### Will you send logs?

No

**Comment by Johennes** [comment]
@Velin92 I suppose interacting with the notification should dismiss any modals before changing the room?

**Comment by ara4n** [comment]
just got another of these; when selecting an image to upload, a push came in; accidentally tapped on it; app then crashed on exiting the image upload prompt.

does this really need design/product?

**Comment by Johennes** [comment]
Stack trace from Sentry: https://sentry.tools.element.io/organizations/element/issues/74603/?project=44&query=is%3Aunresolved&statsPeriod=24h

I guess the problem is that the navigation model breaks from under you by the push notification transition. We should probably just dismiss other modals when navigating from a push to avoid this. Not sure if that really requires product or design input.
