### ISSUE TITLE
App crashes when trying to view user detail in large rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#1237]
### Steps to reproduce

1. In Matrix HQ timeline, click on user detail

#### What did you expect?
I see user detail view

#### What happened instead?
See spinner for a while, nothing happens, then app crashes.

### Your phone model

iPhone 11

### Operating system version

16.5

### Application version

1.1.8 (272)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
This issue is no longer present. The loading indicators were dismissing early meaning you could tap the avatar a second time (or tap a second avatar) which would attempt to push both member details resulting in a crash in the state machine on the second one. The indicator now remains until the list of members is loaded.
