### ISSUE TITLE
Room list shows "Message" as the placeholder for a new room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#1342]
### Steps to reproduce

1. Create a new room
2. Look at timeline

#### What did you expect?
Nothing or a placeholder that says "no messages"

#### What happened instead?
A message preview that says "Message"

![IMG_0259](https://github.com/vector-im/element-x-ios/assets/51663/044d577e-f769-4bfe-b32a-f2ee5d072546)

### Your phone model

iPhone 11

### Operating system version

16.5.1

### Application version

Testflight 1.2.1 (291)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
For context, EXI is falling back to `Message` when the SDK can't provide us with a last message. This was originally because the 2 view sync loop would often not show a last message until the scroll was settled and 20 events loaded in.

The SDK [filters the events](https://github.com/matrix-org/matrix-rust-sdk/blob/68a5f70a85122fed695f2c97d44a4feb0625ac8c/crates/matrix-sdk-base/src/latest_event.rs#L33-L60) that are eligible to just be un-redacted `m.room.message` events. In practice this means we currently show `Message` when the room doesn't receive enough messages through `/sync` to find a displayable one which could be for the following reasons:
- A new room with no `m.room.message` events posted.
- An unused room where the most recent messages are all name/avatar changes or people joining and leaving.
- Scrolling through the room list before the last message is cached, only a single event is loaded until the room becomes visible, at which point 20 are loaded in. In theory this means that you can sometimes see Message whilst waiting for more events (in practice, we have a cache so its not very likely any more).

**Comment by pixlwave** [comment]
Checking with Android, they don't use a placeholder in this case at all, simply leaving it blank. Which in practice sounds like the more correct solution to me.
