### ISSUE TITLE
Bloom pops in

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1666]
### Steps to reproduce

1. Every time you switch to the roomlist, the fancy bloom effect pops in distractingly after about 200ms, making the app feel sluggish or even buggy

#### What did you expect?

Cache the bloom, or worst case fade it in

#### What happened instead?

sluggish pop

### Application version

380

### Will you send logs?

No

**Comment by janogarcia** [comment]
@ara4n @Velin92 It's worth noting that it only happens when the navigation bar in the room list is expanded (initial state, or when the search bar is displayed). For some reason, it doesn't happen when the room list navigation bar is in the collapsed state.

**Comment by Velin92** [comment]
> @ara4n @Velin92 It's worth noting that it only happens when the navigation bar in the room list is expanded (initial state, or when the search bar is displayed). For some reason, it doesn't happen when the room list navigation bar is in the collapsed state.

the problem seems to pobably be related to the fact that the bloom tracks the position of the top left avatar, and when it disappears is unable to track back its position, a solution with constraints seems to solve the problem, however they also made the app crash due to the way constraints + system components + swiftui work very poorly together. For now I have implemented a fade workaround here:
https://github.com/vector-im/element-x-ios/pull/1705

Not fix since that might require more time and investigations, but at least it does not pop in suddenly.

**Comment by janogarcia** [comment]
#1705 Has been merged already. We couldn't pair on fine-tuning the timing for the transition, but we'll do once @Velin92 is back next week.

**Comment by nadonomy** [comment]
Closing as https://github.com/vector-im/element-x-ios/pull/1705 is merged.
