### ISSUE TITLE
Tombstoned rooms must not be displayed in the room list

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#412]
It may require rust or SS update.

**Comment by stefanceriu** [comment]
This is already handled by default by sliding sync https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#tombstones

`By default, sliding sync will not return "old" rooms in lists. This is generally the right thing to do, as many popular rooms have previous versions which would otherwise feature in the room list.`
