### ISSUE TITLE
TestFlight description

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#433]
For a TestFlight release, we need to provide a `What to test?` description.

What wording should we use to explain what is the \(limited\) scope of the TestFlight to the end user?
We may need to explain that EIX supports only simple login/password authentication and requires a matrix server having a SS proxy.

On the SS proxy, we still do not know if we will be able to address the backup solution using the matrix.org proxy for matrix servers which do not have it \(#409\).

**Comment by VolkerJunginger** [comment]
How about this:

Welcome to an early Test version of ElementX.

First of all, don't expect this version to be feature complete.  To use the app you need a Matrix account (or Matrix server having a SlidingSync proxy) and only simple login/password authentication is supported.

Secondly, as this is an early version, things may not work yet as expected or the app may even crash. 

Otherwise, we hope you enjoy the app, and we welcome your feedback: crash reports, improvement ideas, feature requests.

**Comment by VolkerJunginger** [comment]
Is this description accurate? If so I would ask marketing to have another look.

**Comment by manuroe** [comment]
LGTM. I would just modify one sentence for accuracy:

>  To use the app you need a Matrix account (or Matrix server having a SlidingSync proxy) and only simple login/password authentication is supported.

To use the app you need an existing account on a Matrix server having a SlidingSync proxy.  Only simple login/password authentication is supported.

**Comment by VolkerJunginger** [comment]
Welcome to an early test version of ElementX.

First of all, don't expect this version to be feature complete. To use the app you need an existing account on a Matrix server having a SlidingSync proxy. Only simple login/password authentication is supported.

Secondly, as this is an early version, things may not work yet as expected or the app may even crash. 
Otherwise, we hope you enjoy the app, and we welcome your feedback: crash reports, improvement ideas, feature requests.

**Comment by VolkerJunginger** [comment]
Marketing has given a "go".

**Comment by stefanceriu** [comment]
Added to `ASC` -> `Testflight` -> `Test Information` -> `Beta App Information` for both ElX and ElX Nightly
