### ISSUE TITLE
Cancelling a reply/edit can sometimes leave some items dimmed out.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#542]
I think this usually happens if the items are offscreen at the time of cancelling the reply/edit.

Note: The current Figma doesn't show a highlight during [editing](https://www.figma.com/file/G2ulpYxj8I0JzFyQznugwc/Element-X-BBQ-Alpha?node-id=1030%3A47505&t=YhcRnfhmGpuLck3Y-4) or [replying](https://www.figma.com/file/G2ulpYxj8I0JzFyQznugwc/Element-X-BBQ-Alpha?node-id=1166%3A48602&t=YhcRnfhmGpuLck3Y-4) so it may well be enough to simply remove this behaviour.

Nightly 1.0.19

**Comment by Velin92** [comment]
Tested and the dimming works fine for Reply, but actually does not work at all for Edit (is actually not implemented at all in the code).
However since the dimming feature is not present in Figma, I wanted to know if we can remove it or if I should add it to the Edit behaviour too.

Here is a visual example of the dimming for a reply:
![IMG_0137](https://user-images.githubusercontent.com/34335419/220162269-99915967-1c86-478b-b94d-c1a89795a116.PNG)

@callumu
