### ISSUE TITLE
Mac Element Desktop app using catalyst framework

### ISSUE THREAD

**Issue by pszypowicz** [vector-im/element-x-ios#570]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
There's theoretical possibility of building element macOS desktop app, using same code base as ios app, by using catalyst framework.

Have you maybe consider that? Is that something worth doing?

I think that biggest benefit would be shared code base for both ios and ipad/desktop app, and much better/closer integration with macOS \(where current electron version may stand behind\)

**Comment by stefanceriu** [comment]
Initially we were building the RustSDK for Catalyst as well but we removed that when it stopped compiling on Xcode versions newer than `13.2.1` (if I remember correctly). ElementX still runs just fine as an iOS app Apple silicon macs.
Meanwhile we have also refactored the application to be a full SwiftUI one (almost). If at any point we would like to turn this into a fully native Mac app then that would probably be the way to go instead of Catalyst.
