### ISSUE TITLE
Invalid mxids break rust-sdk and break sync entirely.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#761]
### Steps to reproduce

1. Receive a message from a user with an (illegal) utf-8 mxid - e.g. in a `extensions.e2ee.device_lists.left` sync response.
2. Observe that rust-sdk falls over with:

`path="/_matrix/client/unstable/org.matrix.msc3575/sync?timeout=30000"}: matrix_sdk::http_client: Error while sending request: Api(Deserialization(Json(Error("identifier contains invalid characters", line: 1, column: 186275))))`

3. Observe that Element X will never sync again.

#### What did you expect?

We should uphold Postel's Law. Invalid mxids should not DoS EX.

#### What happened instead?

My EX is hosed and i'm going to have to log out & in again to rescue it.

### Application version

Nightly 1.10.8 (20230328180258)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by poljar** [comment]
We can observe Postel's law, but does this actually produce desireable outcomes? Consider the fact that it will likely lead to the following scenario:

1. We get an invalid MXID which we filter out (because it's invalid) but the client otherwise continues operating as normal.
2. Those users are now missing in the room list.
3. Other users report bugs that users with invalid MXIDs are missing. Users with invalid MXIDs don't get keys sent to them so they report UISI bugs.

It seems like this is just papering over a bug in the server and that ultimately we need to fix the server implementation to reject invalid MXIDs (or change the spec to allow them).

**Comment by jplatte** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/1814.

**Comment by poljar** [comment]
There's another case of this, not sure which ID it is exactly, but now we encountered an ID that exceeds the length limit:

```
matrix_sdk_ffi::client: Ignoring sync error: Http(Api(Deserialization(Json(Error("ID exceeds 255 bytes", line: 1, column: 227468)))))
```

**Comment by Hywan** [comment]
Should I assign the task to @jplatte, it seems to be something we should fix on the Ruma' side?

**Comment by jplatte** [comment]
I'm concerned about changing (more) things in Ruma to accomodate for Synapse under-validating its inputs. But yeah, this should probably be assigned to me.

**Comment by poljar** [comment]
There was a conversation about this in chat, people are suggesting that the SDK should not accept these IDs, it should instead filter them out.

Pasting my response to this suggestion here:

> There are three ways to handle this type of response:
>    1. Accept the invalid data.
>    2. Partially deserialize every ID in the response.
>    3. Assume that server-generated IDs will adhere to some agreed upon grammar.
>
> We're currently doing a mix of 1 and 3, most SDKs do 1, absolutely no SDK does 2 and i think that is for a reason.

**Comment by Hywan** [comment]
I think the SDK must not accept invalid data. Whatever the server is, the client must work with valid data only.

**Comment by poljar** [comment]
Fixed by: https://github.com/matrix-org/matrix-rust-sdk/pull/2131
