### ISSUE TITLE
Tapping on rooms in the roomlist sometimes does nothing.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#874]
### Steps to reproduce

1. Foreground app
2. Tap on room in room list
3. It blinks but does nothing

#### What did you expect?

Open the room...

### Application version

nightly 206

### Will you send logs?

Yes

**Comment by ara4n** [comment]
Stefan says:

> Apparently 2023-05-10T23:00:45.554499Z ERROR root: elementx: UserSessionFlowCoordinator.swift:188: Invalid room identifier: !skzJXrrsBeYYMkhqOt:matrix.org. That means slidingSync reports that room or its fullRoom as nil

**Comment by ara4n** [comment]
(rageshake has video)

**Comment by Hywan** [comment]
If the room isn't opening because `get_room` returns nil, it means that the `matrix_sdk::Client::get_room` returns `None`, which means that the room hasn't be created internally when the SlidingSync response has been received. It happens here, https://github.com/matrix-org/matrix-rust-sdk/blob/dab4cdd863435753e0dcf55524faa7d10b4504b2/crates/matrix-sdk-base/src/sliding_sync.rs#L102-L211.

What is weird is that it has worked with other rooms, so it might be a subtle bug.

At first glance, I don't see anything that could forbid a room to be created. I'll take a look at the logs.

**Comment by manuroe** [comment]
Haven't see it for a while.
