### ISSUE TITLE
App UI deadlocks entirely on a fairly regular basis

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#928]
### Steps to reproduce

1. foreground app
2. use it for a bit
3. while scrolling around the roomlist, UI deadlocks entirely
4. get bored after 45s or so
5. background the app
6. ~15s later the OS kills it in the bg and you get a crash popup.

#### What did you expect?

no deadlocks

#### What happened instead?

deadlock.

### Application version

nightly 218

### Will you send logs?

Yes

**Comment by ara4n** [comment]
<img width="950" alt="Screenshot 2023-05-19 at 14 14 45" src="https://github.com/vector-im/element-x-ios/assets/1294269/50c39a48-e6f7-4a72-90ff-9b96ab22c319">

**Comment by bnjbvr** [comment]
(Not sure about this theory, but in case it helps Ivan!) On the iOS code, `startSync` is called when the device is woken up from the background; it will call into the FFI `SlidingSync::sync` method, which creates a new stream, and that _new_ stream `await`s a write lock on the internal message sender. But this lock might be already taken because of the previous stream. If I'm correct here, then possible fixes would be to have `sync()` always refer to a unique, lazily-created stream, or have another internal messaging mechanism that stops previous streams.

**Comment by Hywan** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/1992 for the record.
