### ISSUE TITLE
Self-verification can take a very long time to come through

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#996]
### Steps to reproduce

1. Log in
2. Hit the big button at the top of the roomlist to cross-sign yourself
3. Immediately get a verify prompt on EW
4. Then stare at "waiting for other party" for around 50s
5. Finally see the emoji and confirm them
6. Then stare at the "confirming" prompt for at least 10s

#### What did you expect?

Verif should be instant; after all, the to-device msgs are moving instantly, given the "this device wants you to verify it" prompt pops up instantly.

#### What happened instead?

Inexplicable minute-long delays.

### Application version

228

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Seems to be a proxy problem, took 1 minute to send the request acceptance back to Element X cc @kegsay 

I ran a session verification flow from ElementX to Web and these were the requests and timings, gathered from proxyman and chrome devtools.

Element X Starts the verification flow at `14:21:02.957`
`https://matrix-client.matrix.org/_matrix/client/v3/sendToDevice/m.key.verification.request/da7815984f524bfb96ce75f36dd8aea2`


Web receives the request at `11:21:03 GMT` 
`https://matrix-client.matrix.org/_matrix/client/r0/sync?filter=4&timeout=30000&since=s4041866821_757284974_28467251_2167959244_2204602332_4296663_923620254_7581343280_0_124830`
```
"to_device": {
        "events": [
            {
                "content": {
                    "from_device": "VNETSXRKNU",
                    "transaction_id": "9f5620bc505e4015a760f74372591ce5",
                    "methods": [
                        "m.sas.v1"
                    ],
                    "timestamp": 1686223262955
                },
                "type": "m.key.verification.request",
                "sender": "@stefan.ceriu-element01:matrix.org"
            }
        ]
    },
```

Web accepts the request at `11:21:06 GMT`
`https://matrix-client.matrix.org/_matrix/client/r0/sendToDevice/m.key.verification.ready/m1686223265747.0`
```
{"messages":{"@stefan.ceriu-element01:matrix.org":{"VNETSXRKNU":{"methods":["m.sas.v1","m.qr_code.show.v1","m.reciprocate.v1"],"transaction_id":"9f5620bc505e4015a760f74372591ce5","from_device":"DUWOLXSORN"}}}}
```


Element X  finally gets back the approval 1 minute later `14:22:09.714`
`https://slidingsync.lab.matrix.org/_matrix/client/unstable/org.matrix.msc3575/sync?pos=22&timeout=30000`

```
"extensions": {
    "to_device": {
      "next_batch": "4269791",
      "events": [
        {
          "content": {
            "from_device": "VNETSXRKNU",
            "transaction_id": "9f5620bc505e4015a760f74372591ce5",
            "methods": [
              "m.sas.v1"
            ],
            "timestamp": 1686223262955
          },
          "type": "m.key.verification.request",
          "sender": "@stefan.ceriu-element01:matrix.org"
        },
        {
          "content": {
            "methods": [
              "m.sas.v1",
              "m.qr_code.show.v1",
              "m.reciprocate.v1"
            ],
            "transaction_id": "9f5620bc505e4015a760f74372591ce5",
            "from_device": "DUWOLXSORN"
          },
          "type": "m.key.verification.ready",
          "sender": "@stefan.ceriu-element01:matrix.org"
        }
      ]
    }
  },
```

**Comment by manuroe** [comment]
Related to https://gitlab.element.io/engineering/p2p-dendrite/sliding-sync/-/issues/72.

**Comment by kegsay** [comment]
This is a proxy issue, I'm aware of it and addressing it.

**Comment by kegsay** [comment]
This has been improved since the proxy DB was beefed up, but it still isn't great, with up to 18s spikes occasionally. When I caught an 9s gap, 5s was due to synapse and 4s due to the proxy.

**Comment by ara4n** [comment]
empirically i can't self verify currently. the sequence claims it's cancelled when neither side cancels.

**Comment by hughns** [comment]
@ara4n how has this been for you recently? various changes have happened on the SS proxy that could be helping.

**Comment by manuroe** [comment]
We have just tested with 3 people in parallel. It was instant for one. Good enough for others.
I am reducing the priority.

**Comment by manuroe** [comment]
I am closing it. Reopen with a new rageshake if we still have the problem.
